# Generated by Django 5.1.7 on 2025-03-18 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simplechat', '0002_alter_room_users'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='users',
            field=models.ManyToManyField(blank=True, related_name='rooms', to='users.customuser'),
        ),
    ]
